# Generated by Django 3.2 on 2022-06-27 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("text", models.TextField(verbose_name="text")),
                (
                    "preview_image",
                    models.ImageField(
                        upload_to="article/previews/%Y/%m", verbose_name="preview image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.CreateModel(
            name="ArticleGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="article/gallery/%Y/%m", verbose_name="image"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="articles.article",
                        verbose_name="article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article gallery",
                "verbose_name_plural": "Article galleries",
            },
        ),
    ]
