# Generated by Django 3.2 on 2022-06-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="short_description",
            field=models.CharField(default=1, max_length=255, verbose_name="short description"),
            preserve_default=False,
        ),
    ]
